name = "Implicit3DPlotting"
uuid = "d997a800-832a-4a4c-b340-7dddf3c1ad50"
authors = ["Matthias Himmelmann <matthias.himmelmann@outlook.de>"]
version = "0.2.3"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"

[compat]
GLMakie = "0.1, 0.2"
Meshing = "0.5"
Polyhedra = "0.6"
julia = "1.6"
